# Generated by Django 3.1.6 on 2021-03-13 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('buy', models.DecimalField(decimal_places=3, max_digits=8)),
                ('buy_change', models.IntegerField(default=0)),
                ('sell', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sell_change', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
