# Generated by Django 3.1.6 on 2021-03-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='id',
            new_name='currency_id',
        ),
    ]
