# Generated by Django 3.1.6 on 2021-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='photo',
            field=models.ImageField(default='photo/default.png', upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='photo/default.png', upload_to='photo/'),
        ),
    ]
