# Generated by Django 3.1.6 on 2021-02-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='execution_time_sec',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
