# Generated by Django 3.1.6 on 2021-02-26 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20210223_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
